name: 'gitagent'
description: 'GitHub Action that executes AI-GitOps agents from the prompts in your repo'
author: 'Tal Muskal'
runs:
  using: 'docker'
  image: 'ghcr.io/a5c-ai/gitagent:latest'
  args:
    - --github-token
    - ${{ inputs.github-token }}
    - --log-level
    - ${{ inputs.log-level }}
  
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub personal access token for API access'
    required: false
    default: ${{ github.token }}
  
  log-level:
    description: 'Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)'
    required: false
    default: 'INFO'
  
  log-format:
    description: 'Log format (json, console)'
    required: false
    default: 'json'
  
  max-concurrent-events:
    description: 'Maximum concurrent event processing'
    required: false
    default: '10'
  
  event-timeout:
    description: 'Event processing timeout in seconds'
    required: false
    default: '30'
  
  background-tasks:
    description: 'Enable background task processing'
    required: false
    default: 'true'
  
  metrics-enabled:
    description: 'Enable metrics collection'
    required: false
    default: 'true'
  
  health-check-enabled:
    description: 'Enable health check endpoints'
    required: false
    default: 'true'
  
  structured-logging:
    description: 'Enable structured logging'
    required: false
    default: 'true'
  
  event-storage-enabled:
    description: 'Enable event storage'
    required: false
    default: 'false'
  
  event-storage-path:
    description: 'Path to store event data'
    required: false
    default: '/app/data/events'
  
  git-commit-history-count:
    description: 'Number of commits to retrieve for history context'
    required: false
    default: '10'
  
  git-timeout:
    description: 'Timeout for git operations in seconds'
    required: false
    default: '30'
  
  enabled-events:
    description: 'Comma-separated list of enabled event types (empty means all events)'
    required: false
    default: ''
  
  disabled-events:
    description: 'Comma-separated list of disabled event types'
    required: false
    default: ''
  
  development-mode:
    description: 'Enable development mode (exposes API docs and detailed errors)'
    required: false
    default: 'false'
  
  # Agent Configuration
  agents-enabled:
    description: 'Enable AI agent processing'
    required: false
    default: 'true'
  
  agents-directory:
    description: 'Directory containing agent configuration files'
    required: false
    default: '.github/action-handlers'
  
  # Agent CLI API Keys
  claude-api-key:
    description: 'Anthropic Claude API key'
    required: false
    default: ''
  
  gemini-api-key:
    description: 'Google Gemini API key'
    required: false
    default: ''
  
  openai-api-key:
    description: 'OpenAI API key (used for both OpenAI and Codex agents)'
    required: false
    default: ''
  
  anthropic-api-key:
    description: 'Alternative Anthropic API key'
    required: false
    default: ''
