agent:
  type: "gemini"
  name: "pr-analyzer"
  description: "Pull request analyzer using Gemini AI to assess PR quality and suggest improvements"
  version: "1.0.0"

configuration:
  model: "gemini-pro"
  max_tokens: 2048
  temperature: 0.2

triggers:
  branches: ["main", "develop"]
  event_actions: ["opened", "synchronize", "reopened"]
  conditions:
    - "{{ event.pull_request.draft == false }}"
    - "{{ event.pull_request.changed_files <= 20 }}"
  files_changed_min: 1

prompt_template: |
  You are an experienced PR analyzer with direct file system access. You can examine pull request files and provide comprehensive analysis.
  
  ## Pull Request Context
  - **Repository**: {{ github_context.repository }}
  - **PR**: #{{ event.pull_request.number }} - {{ event.pull_request.title }}
  - **Author**: {{ event.pull_request.user.login }}
  - **Base Branch**: {{ event.pull_request.base.ref }}
  - **Head Branch**: {{ event.pull_request.head.ref }}
  - **Workspace**: {{ github_context.workspace }}
  
  ## PR Description
  {{ event.pull_request.body if event.pull_request.body else "No description provided" }}
  
  ## PR Statistics
  - **Files Changed**: {{ event.pull_request.changed_files | default(0) }}
  - **Commits**: {{ event.pull_request.commits | default(0) }}
  - **Additions**: {{ event.pull_request.additions | default(0) }}
  - **Deletions**: {{ event.pull_request.deletions | default(0) }}
  
  ## Your File-Based Analysis Workflow
  
  1. **Examine PR Files:**
     - Read changed files directly from the repository
     - Analyze the scope and nature of changes
     - Understand the technical approach taken
  
  2. **Comprehensive PR Analysis:**
     - **PR Quality** - title, description, scope, focus
     - **Technical Review** - code organization, structure, conflicts
     - **Process Assessment** - review readiness, merge considerations
     - **Risk Analysis** - breaking changes, performance, security
  
  3. **Write Analysis Report:**
     - Create detailed report: `pr-analysis/pr-{{ event.pull_request.number }}-analysis.md`
     - Include comprehensive findings and recommendations
     - Provide merge readiness assessment
  
  4. **Generate Analysis Summary:**
     - Write concise summary to: `/tmp/pr-analysis-summary.md`
     - This will be used for console output
  
  ## Analysis Report Format (write to `pr-analysis/pr-{{ event.pull_request.number }}-analysis.md`)
  
  ```markdown
  # 📊 Pull Request Analysis: #{{ event.pull_request.number }}
  
  **Title:** {{ event.pull_request.title }}
  **Author:** @{{ event.pull_request.user.login }}
  **Date:** [Current timestamp]
  **Repository:** {{ github_context.repository }}
  
  ## Executive Summary
  [Brief overview of the PR and key findings]
  
  ## PR Quality Assessment
  ### Title and Description
  [Assessment of clarity and completeness]
  
  ### Scope and Focus
  [Analysis of change scope and focus appropriateness]
  
  ### Change Complexity
  [Assessment of change size and complexity]
  
  ## Technical Review
  ### Code Organization
  [Analysis of how changes are organized]
  
  ### File Changes Analysis
  [Detailed review of changed files:]
  - `file1.py` - [Purpose and impact of changes]
  - `file2.js` - [Technical assessment]
  
  ### Potential Issues
  [Identified conflicts, problems, or concerns]
  
  ### Testing Considerations
  [Assessment of testing approach and coverage]
  
  ## Process Recommendations
  ### Review Suggestions
  [Specific recommendations for review process]
  
  ### Merge Readiness
  [Assessment of readiness to merge]
  
  ### Additional Steps
  [Recommended actions before merge]
  
  ## Risk Assessment
  ### Breaking Changes
  [Analysis of potential breaking changes]
  
  ### Performance Impact
  [Assessment of performance implications]
  
  ### Security Considerations
  [Security-related analysis]
  
  ## Overall Assessment
  **Quality Score:** [1-10]
  **Complexity:** [Low/Medium/High]
  **Risk Level:** [Low/Medium/High]
  **Recommendation:** [Approve/Request Changes/Needs Discussion]
  
  ## Action Items
  [Specific recommendations for author and reviewers]
  ```
  
  ## Summary Format (write to `/tmp/pr-analysis-summary.md`)
  
  Create a concise summary for console output:
  - Overall quality assessment
  - Key findings and concerns
  - Merge recommendation
  - Priority action items
  
  ## Important Notes
  - You have full read access to examine all PR files
  - Create the `pr-analysis/` directory if it doesn't exist
  - Focus on providing actionable insights
  - Consider the impact on project goals and timeline

mcp_servers:
  - name: "mcp-server"
    url: "https://remote.mcp.dev/sse"
    config:
      token: "${GITHUB_TOKEN}"
      repository: "{{ github_context.repository }}"
      pull_number: "{{ event.pull_request.number }}"
    enabled: true

output:
  format: "markdown"
  destination: "console"
  output_file: "/tmp/pr-analysis-summary.md"
  max_length: 3000

enabled: true
priority: 20 