agent:
  type: "claude"
  name: "code-reviewer"
  description: "Automated code reviewer using Claude AI to analyze changes and provide feedback"
  version: "1.0.0"

configuration:
  model: "claude-3-sonnet-20241022"
  max_tokens: 4000
  temperature: 0.1
  system_prompt: "You are an expert code reviewer focused on quality, security, and best practices."

triggers:
  branches: ["main", "develop", "feature/*"]
  paths: ["*.py", "*.js", "*.ts", "*.go", "*.java", "*.rs"]
  conditions:
    - "{{ commit_history.total_commits > 0 }}"
    - "{{ event.commits | length > 0 }}"
  files_changed_min: 1
  files_changed_max: 50

prompt_template: |
  # Code Review Request
  
  ## Repository Information
  - **Repository**: {{ github_context.repository }}
  - **Branch**: {{ github_context.ref | replace("refs/heads/", "") }}
  - **Actor**: {{ github_context.actor }}
  - **Event**: {{ github_context.event_name }}
  
  ## Commit History Context
  {% if commit_history %}
  **Recent Commits** ({{ commit_history.total_commits }} total):
  {% for commit in commit_history.commits[:5] %}
  - `{{ commit.sha[:8] }}`: {{ commit.message }} by {{ commit.author_name }}
  {% endfor %}
  {% endif %}
  
  ## Changes to Review
  {% if event.commits %}
  **Commits in this push**:
  {% for commit in event.commits %}
  - **{{ commit.id[:8] }}**: {{ commit.message }}
    - Author: {{ commit.author.name }} <{{ commit.author.email }}>
    - Modified files: {{ commit.modified | length }}, Added: {{ commit.added | length }}, Removed: {{ commit.removed | length }}
  {% endfor %}
  {% endif %}
  
  ## Review Guidelines
  Please provide a comprehensive code review focusing on:
  
  1. **Code Quality**
     - Code structure and organization
     - Naming conventions and clarity
     - Code duplication and DRY principles
     - Error handling and edge cases
  
  2. **Security**
     - Input validation and sanitization
     - Authentication and authorization
     - Data exposure and privacy
     - Dependency vulnerabilities
  
  3. **Performance**
     - Algorithm efficiency
     - Resource usage
     - Caching opportunities
     - Database query optimization
  
  4. **Best Practices**
     - Language-specific conventions
     - Design patterns
     - Testing coverage
     - Documentation quality
  
  5. **Maintainability**
     - Code complexity
     - Modularity and coupling
     - Configuration management
     - Logging and monitoring
  
  ## Output Format
  Please structure your review as:
  
  ### Summary
  Brief overall assessment of the changes.
  
  ### Strengths
  What was done well in these changes.
  
  ### Issues Found
  - **Critical**: Security vulnerabilities, breaking changes
  - **Major**: Performance issues, architectural problems
  - **Minor**: Style issues, minor improvements
  
  ### Recommendations
  Specific actionable recommendations for improvement.
  
  ### Security Assessment
  Specific security-related findings and recommendations.

mcp_servers:
  - name: "github-server"
    url: "github://api"
    config:
      token: "${GITHUB_TOKEN}"
      repository: "{{ github_context.repository }}"
    enabled: true
  
  - name: "filesystem-server"
    url: "file://workspace"
    config:
      root: "${GITHUB_WORKSPACE}"
      allowed_extensions: [".py", ".js", ".ts", ".go", ".java", ".rs", ".md", ".yml", ".yaml", ".json"]
    enabled: true

output:
  format: "markdown"
  destination: "artifact"
  file_path: "code-review-{{ github_context.sha[:8] }}.md"
  max_length: 8000
  template: |
    # Code Review - {{ github_context.repository }}
    
    **Commit**: {{ github_context.sha[:8] }}  
    **Branch**: {{ github_context.ref | replace("refs/heads/", "") }}  
    **Reviewer**: {{ agent.name }}  
    **Date**: {{ "now" | strftime("%Y-%m-%d %H:%M:%S UTC") }}
    
    ---
    
    {{ output }}
    
    ---
    
    *Generated by {{ agent.name }} ({{ agent.type }}) - Version {{ agent.version }}*

enabled: true
priority: 10 