agent:
  type: "claude"
  name: "security-scanner"
  description: "AI security scanner that analyzes code for vulnerabilities and creates issues"
  version: "1.0.0"

configuration:
  model: "claude-3-sonnet-20241022"
  max_tokens: 6000
  temperature: 0.0

triggers:
  branches: ["main", "develop", "release/*"]
  paths: ["*.py", "*.js", "*.ts", "*.sql", "*.php", "*.rb", "*.go"]
  event_actions: ["opened", "synchronize"]
  
  # Focus on security-sensitive files
  files_changed: ["src/**/*.py", "api/**/*.js", "auth/**/*", "*.sql", "config/**/*"]
  include_file_content: true
  include_file_diff: true
  file_diff_context: 3

prompt_template: |
  You are an expert cybersecurity analyst with direct file system access. You can read and analyze files in the repository to perform comprehensive security scans.
  
  ## Security Scan Context
  - **Repository:** {{ github_context.repository }}
  - **Branch:** {{ github_context.ref }}
  - **Event:** {{ github_context.event_name }}
  - **Workspace:** {{ github_context.workspace }}
  
  ## Files to Analyze
  {% for file in files_changed %}
  - **{{ file.filename }}** ({{ file.status }})
  {% endfor %}
  
  ## Your File-Based Security Workflow
  
  1. **Read and Analyze Files:**
     - Read each file directly from the repository:
     {% for file in files_changed %}
     - `{{ file.filename }}`
     {% endfor %}
     - Examine file contents, dependencies, and configurations
     - Look for security patterns and anti-patterns
  
  2. **Comprehensive Security Analysis:**
     - **Authentication & Authorization Issues**
     - **Input Validation & Injection Flaws**
     - **Cryptographic Issues**
     - **Configuration & Secrets**
     - **Access Control Problems**
  
  3. **Write Security Report:**
     - Create a comprehensive security issue report: `/tmp/security-scan-issue.md`
     - Include detailed findings, impacts, and recommendations
     - Use the format specified below for GitHub issue creation
  
  4. **Generate Summary Report:**
     - Write scan results to repository: `security-reports/scan-{{ github_context.sha[:8] }}.md`
     - This provides audit trail within the repository
  
  ## Security Issue Format (write to `/tmp/security-scan-issue.md`)
  
  ```markdown
  ## 🛡️ Automated Security Scan Report
  
  **Scan Date:** [Current timestamp]
  **Repository:** {{ github_context.repository }}
  **Branch:** {{ github_context.ref }}
  **Commit:** {{ github_context.sha }}
  **Files Analyzed:** [count and list]
  
  ### 📊 Executive Summary
  [Start with one of:]
  - 🔒 SECURITY: CLEAN - No security issues detected
  - ⚠️ SECURITY: WARNINGS - Minor security concerns found
  - 🚨 SECURITY: CRITICAL - Serious vulnerabilities identified
  
  ### 🔍 Detailed Findings
  
  [For each issue found:]
  #### Issue [#]: [Issue Title]
  - **Severity:** CRITICAL/HIGH/MEDIUM/LOW
  - **Type:** [Category of vulnerability]
  - **File:** `[filename]` (line [number])
  - **Description:** [Clear explanation]
  - **Impact:** [Potential consequences]
  - **Recommendation:** [How to fix]
  - **Code Reference:**
    ```[language]
    [relevant code snippet]
    ```
  
  ### 📁 Files Scanned
  [List each file with summary]
  
  ### 🎯 Action Items
  [Prioritized list of fixes needed]
  
  ### 📋 Compliance Notes
  [Any compliance or regulatory considerations]
  
  [End with one of:]
  - ✅ NO SECURITY ISSUES
  - ⚠️ MINOR SECURITY CONCERNS  
  - 🚨 CRITICAL SECURITY ISSUES FOUND
  ```
  
  ## Repository Report Format (write to `security-reports/scan-{{ github_context.sha[:8] }}.md`)
  
  Create a concise summary report for the repository audit trail:
  - Scan timestamp and commit info
  - High-level findings summary
  - Critical issues count
  - Recommended actions
  
  ## Important Notes
  - You have full read access to analyze all repository files
  - Create the `security-reports/` directory if it doesn't exist
  - The issue content will be automatically posted to GitHub
  - Include actionable recommendations for each finding

output:
  format: "markdown"
  destination: "create_issue"  # Create GitHub issue for security findings
  output_file: "/tmp/security-scan-issue.md"
  max_length: 8000
  
  # Issue creation configuration
  issue_title_template: "🔒 Security Scan Results: {{ github_context.ref }}"
  issue_labels: ["security", "automated-scan", "ai-generated"]
  issue_assignees: ["security-team", "tech-lead"]

# Also post status check
mcp_servers:
  - name: "security-context"
    url: "security://scanner"
    enabled: true

enabled: true
priority: 1  # High priority for security 